version: '1.1'

services:
    app1:
        build:
            context: .
            dockerfile: ./app1/Dockerfile
        ports:
            - "8000:80"
        container_name: "app1"
        env_file:
            - ./app1/env/.env.local
        volumes:
            - ./app1/code:/code/app
    postgres:
        image: postgres:16.0
        container_name: "postgres"
        command: -c "hba_file=/etc/postgresql/pg_hba.conf"
        environment:
            - TZ=Asia/Tokyo
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        volumes:
            - fastapi_volume:/var/lib/postgresql/data
            - ./postgres/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./postgres/primary/init.sh:/docker-entrypoint-initdb.d/init.sh
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "root", "-d", "postgres"]

    postgres_replica1:
        image: postgres:16.0
        container_name: "postgres_replica1"
        entrypoint: /etc/postgresql/entrypoint.sh
        volumes:
            - fastapi_replica1_volume:/var/lib/postgresql/data
            - ./postgres/read_replica/entrypoint.sh:/etc/postgresql/entrypoint.sh
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "root"]
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    fastapi_volume:
    fastapi_replica1_volume:
